FROM openjdk:17-jdk-slim

WORKDIR /app

COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
COPY src src

RUN chmod +x mvnw
RUN ./mvnw package -DskipTests

EXPOSE 3000

CMD ["java", "-jar", "target/blockchain-0.0.1-SNAPSHOT.jar"]